# Generated by Django 5.0.1 on 2024-01-22 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('btc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('eth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ltc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bnb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('link', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aave', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bch', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('xrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('xlm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
