# Generated by Django 5.0.1 on 2024-01-22 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('personal', 'personal'), ('joint', 'joint'), ('organization', 'organization'), ('visa', 'visa'), ('retirement', 'retirement')], default='personal', max_length=20)),
                ('country_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=17)),
                ('country', models.CharField(max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('key', models.CharField(blank=True, max_length=70, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
