# Generated by Django 5.0.1 on 2024-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('btc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('eth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ltc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bnb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('link', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aave', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bch', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('xrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('xlm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('withdraw_charges', models.IntegerField()),
            ],
        ),
    ]
